### PR TITLE
Simplify condition

### PR DESCRIPTION
**Pull request by matheusbn**

### CODE REVIEW

**Comment by matheusbn** [comment]
I signed it!

**Comment by erickoledadevrel** [comment]
Thanks for contributing! I'm not a fan of throwing the error at the end, since it obscured the correct code path.  What about:

```
var text = [];
if (selection) {
  ...
}
if (!text.length) throw new Error(...);
return text;
```

I think that pattern makes it clearer what the function is supposed to do, vs what is the anomaly.

**Comment by matheusbn** [comment]
Thank you! I agree with that. 
Updated!

**Comment by erickoledadevrel** [comment]
Awesome, thanks again!

**Pull request merged**
