### PR TITLE
"Mangage Google Drive" fixed to "Manage Google Drive"

### PR DESCRIPTION
**Pull request by turquoise-turtle**
The text is licensed public domain if needed because I haven't filled in any agreements

### CODE REVIEW

**Comment by grant** [comment]
@turquoise-turtle [Please look at this](https://github.com/gsuitedevs/apps-script-samples/pull/35#issuecomment-380334420) and I'll merge!

**Comment by grant** [comment]
Bump.

**Comment by turquoise-turtle** [comment]
I signed it

**Comment by grant** [comment]
Thanks!

**Comment by turquoise-turtle** [comment]
You're welcome

**Pull request merged**
